import { AgentSummary } from "../../shared/agentSummary";

export const demoData: AgentSummary[] = [
  {
    week: "Week 1",
    agent: "John Smith",
    firstQuotes: 45,
    secondQuotes: 38,
    submitted: 32,
    freeLooked: 2,
    firstQuoteSmokerPercent: 15.5,
    secondQuoteSmokerPercent: 18.2,
    preferredPercent: 65.0,
    standardPercent: 20.0,
    gradedPercent: 10.0,
    giPercent: 5.0,
    ccPercent: 85.5,
    issuedPaidMinus: 2.1,
    issuedPaidPlus: 87.6,
    smokerPercent: 18.2,
    preLapseCases: 1,
  },
  {
    week: "Week 2",
    agent: "John Smith",
    firstQuotes: 52,
    secondQuotes: 44,
    submitted: 38,
    freeLooked: 1,
    firstQuoteSmokerPercent: 16.8,
    secondQuoteSmokerPercent: 19.1,
    preferredPercent: 68.0,
    standardPercent: 18.0,
    gradedPercent: 9.0,
    giPercent: 5.0,
    ccPercent: 88.2,
    issuedPaidMinus: 1.8,
    issuedPaidPlus: 90.0,
    smokerPercent: 19.1,
    preLapseCases: 0,
  },
  {
    week: "Week 1",
    agent: "Sarah Johnson",
    firstQuotes: 38,
    secondQuotes: 32,
    submitted: 28,
    freeLooked: 3,
    firstQuoteSmokerPercent: 12.3,
    secondQuoteSmokerPercent: 14.5,
    preferredPercent: 72.0,
    standardPercent: 15.0,
    gradedPercent: 8.0,
    giPercent: 5.0,
    ccPercent: 82.1,
    issuedPaidMinus: 3.2,
    issuedPaidPlus: 85.3,
    smokerPercent: 14.5,
    preLapseCases: 2,
  },
  {
    week: "Week 2",
    agent: "Sarah Johnson",
    firstQuotes: 41,
    secondQuotes: 35,
    submitted: 31,
    freeLooked: 2,
    firstQuoteSmokerPercent: 13.1,
    secondQuoteSmokerPercent: 15.2,
    preferredPercent: 74.0,
    standardPercent: 14.0,
    gradedPercent: 7.0,
    giPercent: 5.0,
    ccPercent: 84.6,
    issuedPaidMinus: 2.8,
    issuedPaidPlus: 87.4,
    smokerPercent: 15.2,
    preLapseCases: 1,
  },
  {
    week: "Week 1",
    agent: "Mike Davis",
    firstQuotes: 29,
    secondQuotes: 24,
    submitted: 19,
    freeLooked: 4,
    firstQuoteSmokerPercent: 22.1,
    secondQuoteSmokerPercent: 25.3,
    preferredPercent: 45.0,
    standardPercent: 25.0,
    gradedPercent: 20.0,
    giPercent: 10.0,
    ccPercent: 76.8,
    issuedPaidMinus: 5.2,
    issuedPaidPlus: 82.0,
    smokerPercent: 25.3,
    preLapseCases: 3,
  },
  {
    week: "Week 2",
    agent: "Mike Davis",
    firstQuotes: 33,
    secondQuotes: 28,
    submitted: 22,
    freeLooked: 3,
    firstQuoteSmokerPercent: 21.5,
    secondQuoteSmokerPercent: 24.8,
    preferredPercent: 48.0,
    standardPercent: 24.0,
    gradedPercent: 18.0,
    giPercent: 10.0,
    ccPercent: 78.9,
    issuedPaidMinus: 4.8,
    issuedPaidPlus: 83.7,
    smokerPercent: 24.8,
    preLapseCases: 2,
  },
  // Add totals
  {
    week: "Total",
    agent: "John Smith",
    firstQuotes: 97,
    secondQuotes: 82,
    submitted: 70,
    freeLooked: 3,
    firstQuoteSmokerPercent: 16.2,
    secondQuoteSmokerPercent: 18.7,
    preferredPercent: 66.5,
    standardPercent: 19.0,
    gradedPercent: 9.5,
    giPercent: 5.0,
    ccPercent: 86.9,
    issuedPaidMinus: 1.95,
    issuedPaidPlus: 88.8,
    smokerPercent: 18.7,
    preLapseCases: 1,
  },
  {
    week: "Total",
    agent: "Sarah Johnson",
    firstQuotes: 79,
    secondQuotes: 67,
    submitted: 59,
    freeLooked: 5,
    firstQuoteSmokerPercent: 12.7,
    secondQuoteSmokerPercent: 14.9,
    preferredPercent: 73.0,
    standardPercent: 14.5,
    gradedPercent: 7.5,
    giPercent: 5.0,
    ccPercent: 83.4,
    issuedPaidMinus: 3.0,
    issuedPaidPlus: 86.4,
    smokerPercent: 14.9,
    preLapseCases: 3,
  },
  {
    week: "Total",
    agent: "Mike Davis",
    firstQuotes: 62,
    secondQuotes: 52,
    submitted: 41,
    freeLooked: 7,
    firstQuoteSmokerPercent: 21.8,
    secondQuoteSmokerPercent: 25.1,
    preferredPercent: 46.5,
    standardPercent: 24.5,
    gradedPercent: 19.0,
    giPercent: 10.0,
    ccPercent: 77.9,
    issuedPaidMinus: 5.0,
    issuedPaidPlus: 82.9,
    smokerPercent: 25.1,
    preLapseCases: 5,
  },
];
